#!/bin/sh
cd ./dependencies/
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install ruby-install
ruby-install ruby 2.2.0
sudo gem update --system
gem install bundler
bundle install